version: '3.5'

services:
  symfony-web:
    container_name: symfony-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 8000:80
    volumes:
      - ./public:/appdata/www/public
    networks:
      - symfony-network
    depends_on:
      - symfony-backend

  symfony-backend:
    container_name: symfony-backend
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
  #    - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - symfony-network
    depends_on:
      - symfony-db

  symfony-db:
    container_name: symfony-db
    image: mysql:8
    ports:
      - 40000:3306
    env_file:
      - ${PWD}/docker.env
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - symfony-database-data:/var/lib/mysql
    networks:
      - symfony-network

volumes:
  symfony-database-data:

networks:
  symfony-network:
    external: true
